version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=filedb

  metadata-service:
    build: ./metadata-service
    ports:
      - "5004:5004"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/filedb
    depends_on:
      - postgres

  upload-service:
    build: ./upload-service
    ports:
      - "5001:5001"
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - METADATA_SVC_URL=http://metadata-service:5004
    depends_on:
      - localstack
      - metadata-service

  download-service:
    build: ./download-service
    ports:
      - "5002:5002"
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - METADATA_SVC_URL=http://metadata-service:5004
    depends_on:
      - localstack
      - metadata-service

  ui-service:
    build: ./ui-service
    ports:
      - "5003:5003"
    environment:
      - DOWNLOAD_SVC_URL=http://download-service:5002
    depends_on:
      - download-service